# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Item.create([
              { name: 'cash' },
              { name: 'tickets' },
              { name: 'passport' },
              { name: "driver's license" },
              { name: 'lotion' },
              { name: 'conditioner' },
              { name: 'floss' },
              { name: 'hair products' },
              { name: 'lip balm' },
              { name: 'nail clippers' },
              { name: 'soap' },
              { name: 'toothbrush' },
              { name: 'face wash' },
              { name: 'hair dryer' },
              { name: 'razor' },
              { name: 'shaving cream' },
              { name: 'tissues' },
              { name: 'Kleenex' },
              { name: 'toothpaste' },
              { name: 'cologne / perfume' },
              { name: 'makeup' },
              { name: 'deodorant' },
              { name: 'hairbrush' },
              { name: 'comb' },
              { name: 'hand sanitizer' },
              { name: 'shampoo' },
              { name: 'wash cloth' },
              { name: 'towel' },
              { name: 'dress' },
              { name: 'gloves' },
              { name: 'mittens' },
              { name: 'jewelry' },
              { name: 'pajamas' },
              { name: 'raincoat' },
              { name: 'shirt' },
              { name: 'suit' },
              { name: 'swimsuit' },
              { name: 'underwear' },
              { name: 'hat' },
              { name: 'belt' },
              { name: 'shoes' },
              { name: 'sandals' },
              { name: 'pants' },
              { name: 'shorts' },
              { name: 'skirt' },
              { name: 'sweater' },
              { name: 'jacket' },
              { name: 'watch' },
              { name: 'hiking shoes' },
              { name: 'boots' },
              { name: 'fleece' },
              { name: 'rain boots' },
              { name: 'scarf' },
              { name: 'sweatshirt' },
              { name: 'allergy medication' },
              { name: 'bandages' },
              { name: 'first aid kit' },
              { name: 'camera' },
              { name: 'laptop' },
              { name: 'laptop charger' },
              { name: 'phone' },
              { name: 'phone cord' },
              { name: 'book' },
              { name: 'magazine' },
              { name: 'blanket' },
              { name: 'map' },
              { name: 'compass' },
              { name: 'insect repellent' },
              { name: 'sunscreen' },
              { name: 'bug spray' },
              { name: 'sleeping bag' },
              { name: 'tent' },
              { name: 'sleeping pad' },
              { name: 'water bottle' },
              { name: 'stove' },
              { name: 'lighter' },
              { name: 'matches' },
              { name: 'sunglasses' },
              { name: 'headlamp' }
            ])
